package by.tc.rentalshop.controller;

public enum CommandsNames {// почему название во множественном числе?
	
	ADD_SPORTEQUIPMENT, EDIT_SPORTEQUIPMENT, DELETE_SPORTEQUIPMENT, 
	REGISTRATION, SIGN_IN, EDIT_USER, DELETE_USER, 
	RENT_EQUIPMENT,RETURN_EQUIPMENT,
	SHOW_EQUIPMENT,SHOW_USERS_EQUIPMENT,
	SEARCH_EQUIPMENT,
	WRONG_REQUEST;

}
